worker_processes auto;
events {
    worker_connections 1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream stream_backend {
        server stream-server:8080;
    }

    server {
        listen 80;

        # Прокси клиентской части
        location / {
            proxy_pass http://client:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Прокси для потокового сервера
        location /stream {
            proxy_pass http://stream_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Доступ к загруженным видео
        location /videos/ {
            alias /app/videos/;
            autoindex on; # Включить просмотр содержимого папки (опционально)
        }

        location /stub_status {
            stub_status on;
            allow all;
        }
    }
}