apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app-namespace
data:
  nginx.conf: |
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        upstream stream_backend {
            server stream-server:8080;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://client:3000;
            }
            location /stream {
                proxy_pass http://stream_backend;
            }
        }
    }

